
/* eslint-disable eslint-comments/no-unlimited-disable */
/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by laravel-typescriptable
declare namespace App.Models {

  export interface User {
    verified: boolean;
    name: string;
    email: string;
    imageUrl?: string;
    email_verified_at?: string;
    password: string;
  }
  export interface Deck {
    name: string;
    description: string;
    drawers?: string[];
    flashcards?: string[];
    difficulty?: "easy" | "medium" | "hard" | "very hard" | "expert"
    total: number;
    new: number;
    due: number;
    leech: number;
    suspended: number;
    owners?: User[];
    coverUrl?: string;
    properties: Property[];

  }
  export interface Property {
    name: string;
    value: string;
    type: "text" | "number" | "date" | "time" | "datetime" | "color" | "range" | "file" | "checkbox" | "select"
  }

  export interface Drawer {
    icon: string;
    name: string;
    description: string;
    tags: string[];
    decks?: App.Models.Deck[];
    vaultUrl?: string;
  }


  export interface MultipleChoiceOption {
    value: string;
    isCorrect: boolean;
    imgPath: string;
  }

  export interface Tag {
    name: string;
    color: string;
  }

  export interface Flashcard {
    number: number;
    question: string;
    tags?: Tag[];
    decks?: Deck[];
    type:
    | 'Multiple Choice'
    | 'True/False'
    | 'Fill in the Blank'
    | 'Short Answer'
    | 'Matching'
    | 'Essay'
    | 'Diagram'
    | 'Flashcard'
    | 'Steps';
    level?: string;
    callout?: string;
    options?: MultipleChoiceOption[];
  }
}

