#path > docker-compose.yml

version: '3.7'

services:

  # mongodb:
  #   image: mongo:latest
  #   env_file:
  #     - .env
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - mongodb_data_container:/data/db

  nestapi:
    container_name: nestapi
    build: .
    command: npm run start:prod
    # Uncomment below lines only if you are developing. 
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - mqtttest
    environment:
      - env
      - connectUrl
      - connectTimeout
      - username
      - password
      - reconnectPeriod

    ports:
      - ${APP_PORT}:${APP_PORT}
    env_file:
      - .env
    # depends_on:
    #   - mongodb
    restart: always
  
  mqtt-broker:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    ports:
      - "1883:1883"
    networks:
      - mqtttest
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

networks:
  mqtttest:
    name: mqtttest
volumes:
  data: ~
  # mongodb_data_container:
